# Generated by Django 5.0.6 on 2024-06-01 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('urlFoto', models.CharField(max_length=255)),
                ('urlUbicacion', models.CharField(max_length=255)),
                ('fechaDeNacimiento', models.DateField()),
                ('especie', models.CharField(max_length=45)),
                ('colorDePelo', models.CharField(max_length=100)),
                ('pesoKg', models.FloatField()),
                ('isEsterilizado', models.BooleanField()),
                ('observaciones', models.CharField(max_length=250)),
                ('isAdoptado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('fechaDeNacimiento', models.DateField()),
                ('contrasenia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeAdopcion', models.DateField(auto_now_add=True)),
                ('nombreAdoptante', models.CharField(max_length=45)),
                ('apellidoAdoptante', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('calle', models.CharField(max_length=45)),
                ('numero', models.IntegerField()),
                ('localidad', models.CharField(max_length=45)),
                ('provincia', models.CharField(max_length=45)),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
